[package]
name = "notes-watcher"
version = "0.1.0"
authors = ["John Gilliland <john.gilliland@rndgroup.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.12"
